language: generic
sudo: required
branches:
    only:
        - travis-ci
matrix:
    include:
        - os: linux
          env: BUILDING_FOR_OS=linux CXX=g++-7 CC=gcc-7
          addons:
              apt:
                  packages:
                      - g++-7
                      - valgrind
                      - gawk
                      - sed
                      - lcov
                      - libboost-dev
                  sources: &sources
                      - ubuntu-toolchain-r-test
                  before_script:
                      - export CMAKE_BUILD_FLAGS="-DCOVERAGE=ON"
                      - gem install coveralls-lcov
                      - mkdir -p build
                      - cd build
                      - lcov --directory . --zerocounters
                      - cd ..
                  after_success:
                      - cd build
                      - echo "========================================="
                      - ctest
                      - cd ..
                      - lcov --directory . --capture --output-file coverage.info # capture coverage info
                      - lcov --list coverage.info # debug before upload
                      - coveralls-lcov coverage.info # for open source
                      - echo "========================================="
        - os: linux
          env: BUILDING_FOR_OS=linux CXX=g++-7 CC=gcc-7
          addons:
              apt:
                  packages:
                      - g++-7
                      - valgrind
                      - gawk
                      - sed
                      - lcov
                      - libboost-dev
                  sources: &sources
                      - ubuntu-toolchain-r-test
        - os: osx
          osx_image: xcode10.1
          env: BUILDING_FOR_OS=osx
          addons:
              apt:
                  packages:
                      - boost
script:
    - echo "========================================="
    - mkdir -p build
    - cd build
    - cmake $CMAKE_BUILD_FLAGS ..
    - make
    - echo "========================================="
    - cd ..
notifications:
    email:
        recipients:
            - sergiy@skalelabs.com
        on_success: change
        on_failure: always
